const $=s=>document.querySelector(s), messages=$('#messages'), traceBox=$('#trace'), sourcesBox=$('#sources');
function esc(v){return String(v).replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]))}
function scroll(){messages.scrollTop=messages.scrollHeight}
function message(text,kind){const el=document.createElement('article');el.className=`message ${kind}`;el.innerHTML=kind==='assistant'?`<div class="avatar">R</div><div><div class="bubble"></div><time>RAG Assistant · streaming</time></div>`:`<div><div class="bubble">${esc(text)}</div><time>You</time></div>`;messages.append(el);scroll();return kind==='assistant'?el.querySelector('.bubble'):null}
function addTrace(t){if(traceBox.classList.contains('empty')){traceBox.classList.remove('empty');traceBox.innerHTML=''}const el=document.createElement('div');el.className=`trace-item ${t.status}`;el.innerHTML=`<i class="trace-dot"></i><div><div class="trace-name">${esc(t.step)} <span class="trace-meta">${esc(t.status)} · ${t.duration_ms||0}ms</span></div><div class="trace-desc">${esc(t.reasoning_summary||'')}</div></div>`;traceBox.append(el);$('#traceCount').textContent=traceBox.children.length}
function drawSources(items){sourcesBox.classList.remove('empty');sourcesBox.innerHTML=items.length?items.map((s,i)=>`<article class="source"><div class="source-top"><span>#${i+1} · ${esc(s.source)}</span><span>${s.score}</span></div><div class="badges"><i class="badge">${esc(s.type)}</i><i class="badge">${esc(s.customer_role)}</i><i class="badge">${esc(s.retrieval_source)}</i></div><p>${esc(s.content_preview)}</p></article>`).join(''):'No evidence matched the configured threshold.';$('#sourceCount').textContent=items.length}
function metrics(m){$('#metrics').innerHTML=`<div><small>Total latency</small><b>${m.total_latency_ms??'—'} ms</b></div><div><small>Est. tokens</small><b>${m.estimated_tokens??'—'}</b></div><div><small>Top K</small><b>${m.top_k??5}</b></div><div><small>Threshold</small><b>${m.score_threshold??'.10'}</b></div>`}
async function ask(query){query=query.trim();if(!query)return;message(query,'user');$('#query').value='';$('#sendBtn').disabled=true;const bubble=message('','assistant');traceBox.className='trace';traceBox.innerHTML='';$('#traceCount').textContent='0';drawSources([]);metrics({});try{const r=await fetch(`/api/chat/stream?query=${encodeURIComponent(query)}`);const reader=r.body.getReader(), decoder=new TextDecoder();let pending='';while(true){const {value,done}=await reader.read();if(done)break;pending+=decoder.decode(value,{stream:true});const events=pending.split('\n\n');pending=events.pop();for(const raw of events){const kind=(raw.match(/^event: (.+)$/m)||[])[1], data=(raw.match(/^data: (.+)$/m)||[])[1];if(!data)continue;const payload=JSON.parse(data);if(kind==='delta'){bubble.textContent+=payload.text;scroll()}if(kind==='trace')addTrace(payload);if(kind==='complete'){drawSources(payload.sources);metrics(payload.metrics)}}}}catch(e){bubble.textContent='Unable to reach the local demo server.'}finally{$('#sendBtn').disabled=false}}
$('#chatForm').addEventListener('submit',e=>{e.preventDefault();ask($('#query').value)});$('#query').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();ask(e.target.value)}});document.querySelectorAll('.suggestions button').forEach(b=>b.onclick=()=>ask(b.textContent));$('#clearBtn').onclick=()=>{messages.innerHTML='';traceBox.className='trace empty';traceBox.textContent='Trace events will appear here.';sourcesBox.className='sources empty';sourcesBox.textContent='Run a query to inspect retrieved evidence.';metrics({})};$('#exportBtn').onclick=()=>window.open('/api/logs','_blank');
fetch('/api/status').then(r=>r.json()).then(s=>{const c=$('#checkpoints');c.innerHTML=s.checkpoints.map(x=>`<section class="cp"><div class="cp-top"><span class="cp-id">${x.id}</span><span class="cp-title">${x.title}</span><i class="dot ${x.state==='attention'?'attention':''}"></i></div><ul>${x.items.map(i=>`<li>${esc(i)}</li>`).join('')}</ul></section>`).join('');$('#config').innerHTML=Object.entries(s.config).map(([k,v])=>`${k}: ${v}`).join('<br>')}).catch(()=>{});
